### ISSUE TITLE
Backend trait with TokenStream

### ISSUE THREAD

**Issue by v0-e** [librasn/compiler#18]
PR #17 introduced the `generate()` method into the `Backend` trait,
```Rust
fn generate(&self, tld: ToplevelDefinition) -> Result<TokenStream, GeneratorError>;
```
However, based on my understanding, `TokenStream` is specialized for Rust tokens, which contradicts the intention of allowing custom `Backend`s for other language bindings.

**Comment by 6d7a** [comment]
That is indeed something that should change, thank you for pointing that out. Feel free to open a PR.
