### ISSUE TITLE
Issue with DEFAULT {} in SEQUENCE OF Type

### ISSUE THREAD

**Issue by dudycz** [librasn/compiler#2]
Following example from standard X.680 document (slightly simplified) emits warning: _Unidentified generating bindings for : Unexpectedly encountered unlinked struct-like ASN1 value!_ and skips generation of PersonelRecord:

```
ExampleFromX680Spec DEFINITIONS AUTOMATIC TAGS ::=

BEGIN

PersonnelRecord ::=  SET {
        title VisibleString,
        children SEQUENCE OF VisibleString DEFAULT {}
}

END
```

**Comment by 6d7a** [comment]
Thank you for your issue. The behavior should habe been fixed in #3.
