### ISSUE TITLE
Compiler config to disable generation of new method

### ISSUE THREAD

**Issue by dudycz** [librasn/compiler#23]
Hello,

In case of complex and big ASN1 definitions (like the ones from 3gpp) generated new() methods are causing clippy warnings:
`"this function has too many arguments"`
Having an option to choose whether to generate new or not would solve this kind of issue.

**Comment by 6d7a** [comment]
Thank you for your issue. The generated `new` constructors are provided to create instances of `non_exhaustive` structs, as these cannot be constructed with a `StructExpression`. If we don't want to plainly ignore the clippy warning in the generated bindings, we would need to generate another way of constructing `non_exhaustive` types, for example a builder. To be honest, I would simply `#![allow(clippy::too_many_arguments)]`, but if you feel motivated to implement a more elegant solution I'd be more than happy to review it.

**Comment by dudycz** [comment]
Do you mean to add `#![allow(clippy::too_many_arguments)]` in the generated module, right? It would be great and solve this problem.

**Comment by 6d7a** [comment]
Yes, it's merely a matter of adding `too_many_arguments` to the allowed lints [here](https://github.com/librasn/compiler/blob/31d23688f4603da3841bd734bf4c023b17ddca84/rasn-compiler/src/generator/rasn/mod.rs#L116).

**Comment by shahn** [comment]
I believe this could be closed with #29, not sure why it did not auto-close.
