### ISSUE TITLE
Support for recursive types

### ISSUE THREAD

**Issue by nathaniel-bennett** [librasn/compiler#37]
LDAP v3 has a `Filter` type that is defined recursively--it's specifically a `CHOICE` of several options, one of which is a set of `Filter`s (see [here](https://github.com/vlm/ldap-server-example/blob/ef02c57175b00237b25da453e761e66c2a0e0f2c/Lightweight-Directory-Access-Protocol-V3.asn1#L204). Compiling this spec using the current version of the `rasn-compiler` leads to rust code that won't compile due to infinite-sized types.

Is `rasn` meant to support recursive types? If so, this might be a bug specifically in the compiler.

**Comment by Nicceboy** [comment]
Just in case in the meantime, if you have missed it, manually written LDAP is here: https://github.com/librasn/rasn/tree/main/standards/ldap

**Comment by nathaniel-bennett** [comment]
I did end up seeing that--thanks though!

**Comment by Nicceboy** [comment]
I believe that the temporal solution for your problem currently is manually boxing the recursive types with Box<> (as in the manually written standard) while the compiler is not currently doing that automatically. It should fix the cases of recursive types. `rasn` itself can encode and decode boxed types correctly.
