### ISSUE TITLE
imports part parsing error

### ISSUE THREAD

**Issue by yorkz1994** [librasn/compiler#4]
Hi,

I am trying the online tool https://librasn.github.io/, but got an error.

It seems that it does not support multiple FROM in IMPORTS like below:
```
IMPORTS

	Criticality,
	Presence,
	PrivateIE-ID,
	ProtocolExtensionID,
	ProtocolIE-ID
FROM NGAP-CommonDataTypes

	maxPrivateIEs,
	maxProtocolExtensions,
	maxProtocolIEs
FROM NGAP-Constants;
```
If I remove the first FROM, then there is no error.
Sample ASN file attached.
[ngap_container.zip](https://github.com/librasn/compiler/files/14720261/ngap_container.zip)

**Comment by 6d7a** [comment]
Thanks for your issue and the example module. #5 fixes the particular issue with imports that you encountered, so I'll close this here and will update librasn.github.io in the next days. However, I saw that the NGAP protocol you were trying to compile needs some features that are not yet covered by the compiler. I'll see what I can do, though. Would be cool to generate a working NGAP representation.

**Comment by yorkz1994** [comment]
Thanks for the quick fix.
The file I attached is only one part of NGAP just used for this issue.
I attach whole NGAP files for your reference.

It will be a great achievement if you can make it work.
[ngap_asn.zip](https://github.com/librasn/compiler/files/14729739/ngap_asn.zip)
