### ISSUE TITLE
MatchingError(Tag) when parsing RRC module.

### ISSUE THREAD

**Issue by XAMPPRocky** [librasn/compiler#46]
When attempting to parse the module in the linked module I got the following error.

Module: https://www.nrexplained.com/rrc-txt/h60

```
Encountered error while parsing MatchingError(Tag) - Error matching ASN syntax while parsing:SetupRelease { ElementTypeParam } ::= CHOICE { 
    release         NULL,
    setup           ElementTypeParam 
} 
```

**Comment by 6d7a** [comment]
Thank you for your issue. Release `v0.5.3` generates bindings for the linked ASN.1 successfully, although I had to fix three typos in the ASN.1 sources. Let me know if you run into any issues with the generated bindings.
