### ISSUE TITLE
Parse error on sequence constraint

### ISSUE THREAD

**Issue by yodang** [librasn/compiler#59]
Hello !

I have encountered a parsing issue with this ASN.1 module:
https://forge.etsi.org/rep/ITS/asn1/sec_ts103097/-/blob/release2/EtsiTs103097Module.asn

I narrowed it down to the following expressions which both try to set a constraint on a list of elements.
On line 41:
`certificate ((WITH COMPONENT (EtsiTs103097Certificate))^(SIZE(1)))`
On line 45:
```
recipients  (WITH COMPONENT (
        (WITH COMPONENTS {..., 
          pskRecipInfo ABSENT,
          symmRecipInfo ABSENT,
          rekRecipInfo ABSENT
        })
      ))
```

As far as I can tell, this occurs before any of the imported modules are needed.

Cheers

**Comment by kurkpitaine** [comment]
I had those issues on the same standard. 
These constraints are safe to ignore at compile stage, but you need to implement them yourself.
Example of what I have done available [here.](https://github.com/kurkpitaine/veloce/blob/0d55a0a8b06402bb1e8fa64ab0985eb40b4e0499/veloce/src/security/certificate/mod.rs#L201)

**Comment by Nicceboy** [comment]
I am soon making PR in rasn/standards to include these as well with all checks.

**Comment by kurkpitaine** [comment]
If you have a repo where I can grab these @Nicceboy

**Comment by Nicceboy** [comment]
> If you have a repo where I can grab these @Nicceboy

They are currently in private repo but I will let you know. There is still some work to do as I wanted to add build pattern constructors. Maybe that is something that compiler could also support some day, or it would be derive macro in `rasn`. There are few third-party crates that provides these but I am not sure yet if they are the best option.

**Comment by Nicceboy** [comment]
@6d7a I think there is still problem on parsing the `EtsiTs103097Module.asn`. It produces only partial output and skips some types. Those types uses parametrization so maybe it is intentionally left as not implemented yet?

Currently the following is included: 

```rust
pub mod etsi_ts103097_module {
    extern crate alloc;
    use super::etsi_ts103097_extension_module::ExtensionModuleVersion;
    use super::ieee1609_dot2::{Certificate, Ieee1609Dot2Data};
    use core::borrow::Borrow;
    use lazy_static::lazy_static;
    use rasn::prelude::*;
    #[derive(AsnType, Debug, Clone, Decode, Encode, PartialEq, Eq, Hash)]
    #[rasn(delegate)]
    pub struct EtsiTs103097Certificate(pub Certificate);
    #[derive(AsnType, Debug, Clone, Decode, Encode, PartialEq, Eq, Hash)]
    #[rasn(delegate)]
    pub struct EtsiTs103097Data(pub Ieee1609Dot2Data);
    #[derive(AsnType, Debug, Clone, Decode, Encode, PartialEq, Eq, Hash)]
    #[rasn(delegate, identifier = "EtsiTs103097Data-SignedExternalPayload")]
    pub struct EtsiTs103097DataSignedExternalPayload(pub EtsiTs103097Data);
}
```

With

```rust
use rasn_compiler::prelude::*;
use std::path::PathBuf;

fn main() {

    match Compiler::<RasnBackend, _>::new()
        .add_asn_sources_by_path(
            [
                PathBuf::from("../sec_ts103097/EtsiTs103097ExtensionModule.asn"),
                PathBuf::from("../sec_ts103097/EtsiTs103097Module.asn"),
            ]
            .iter(),
        )
        .set_output_path(PathBuf::from("./asn/generated.rs"))
        .compile()
    {
        Ok(warnings /* Vec<Box<dyn Error>> */) => {
            dbg!(warnings);
        }
        Err(error /* Box<dyn Error> */) => {
            dbg!(error);
        }
    }
}
```

**Comment by 6d7a** [comment]
Unfortunately, we cannot represent parameterized types as rust generics, yet. That's why the compiler does not generate bindings for parameterized type definitions. However, the actual invocations of the parameterized types should generate bindings. For example, for the ASN.1
```
TestParam { ParamType } ::= SEQUENCE {
	inner ParamType
}

TestImpl ::= TestParam{INTEGER}
```
the compiler generates
```rust
#[derive(AsnType, Debug, Clone, Decode, Encode, PartialEq, Eq, Hash)]
#[rasn(automatic_tags)]
pub struct TestImpl {
    pub inner: Integer,
}
```
