### ISSUE TITLE
Snake case conversion and text-based encodings

### ISSUE THREAD

**Issue by v0-e** [librasn/compiler#6]
Hi @6d7a,
Just want to start by saying a big thank you for the awesome work on the compiler! 

On the issue, the compiler is currently replacing uppercase letters of ASN.1 identifiers to an underscore and the respective lowercase. For example the [ETSI ITS ItsPduHeader](https://forge.etsi.org/rep/ITS/asn1/cdd_ts102894_2/-/blob/v1.3.1/ITS-Container.asn#L9) is currently compiled into (using https://librasn.github.io):
```
#[derive(AsnType, Debug, Clone, Decode, Encode, Default, PartialEq)]
#[rasn(automatic_tags)]
pub struct ItsPduHeader {
    #[rasn(value("0..=255"))]
    pub protocol_version: u8,
    #[rasn(value("0..=255"))]
    pub message_i_d: u8,
    pub station_i_d: StationID,
}
impl ItsPduHeader {
    pub fn new(protocol_version: u8, message_i_d: u8, station_i_d: StationID) -> Self {
        Self {
            protocol_version,
            message_i_d,
            station_i_d,
        }
    }
}
```
That is, `protocolVersion` is converted to `protocol_version`, `messageID` to `message_i_d`, and `stationID` to `station_i_d`.
In the current JER implementation, `rasn` uses the struct field names to encode the JSON names of name/value pairs.
Instead of,
```
{"protocolVersion":1,"messageID":5,"stationID":999}
```
we have,
```
{"protocol_version":1,"message_i_d":5,"station_i_d":999}
```
Which goes a bit against X.697 27.3.2 a) 2021.

Could we add an option, or disable the conversion altogether, to preserve the original ASN.1 identifiers format in the compiler?

**Comment by 6d7a** [comment]
As of release 0.1.2, the compiler generates the appropriate `identifier` annotation. I agree that further along, the identifier conversion should become configurable, but let's leave that for another PR.
